version: '3.8'

services:
  grafana-aliyun:
    build: .
    container_name: grafana-aliyun
    ports:
      - "80:3000"  # Map to port 80 for easier access
    environment:
      - GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=aliyun-log-service-datasource
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SERVER_ROOT_URL=http://${PUBLIC_IP:-localhost}
    volumes:
      - grafana-storage:/var/lib/grafana
    restart: unless-stopped
    networks:
      - grafana-network

volumes:
  grafana-storage:
    driver: local

networks:
  grafana-network:
    driver: bridge

